### ISSUE TITLE
[BUG] ID3: Only first WOAR frame is kept

### ISSUE THREAD

**Issue by aw-was-here** [tinytag/tinytag#206]
**Describe the bug**
According to the ID3 spec, the `WOAR` frame may appear multiple times

**To Reproduce**

1. tinytag open an MP3 with multiple `WOAR` frame
2. see that `extra["url"]` only has the first entry and not the second

**Expected behavior**
`extra["url"]` should be an (ordered) list wit all `WOAR` frame

**Sample File**
[example](https://github.com/whatsnowplaying/whats-now-playing/blob/tt/tests/audio/multiwebsite.mp3)

**Comment by aw-was-here** [comment]
Looks like most of the website tags have the same problem.

**Comment by mathiascode** [comment]
This will require special handling similar to artists and genres. Which types of URLs are you interested in?

**Comment by aw-was-here** [comment]
I'm particularly interested in the artist websites (e.g., equivalent of WOAR under ID3).  Since 2.0 is going to be incompatible, maybe this would be a good time for TinyTag to automatically put things in lists if it detects more than on frame for a field, regardless of the frame type?

**Comment by mathiascode** [comment]
> Since 2.0 is going to be incompatible, maybe this would be a good time for TinyTag to automatically put things in lists if it detects more than on frame for a field, regardless of the frame type?

I don't think doing this automatically this is a good idea. Returned types should be predictable and consistent, we can't just switch between a string/integer and list.

How about keeping non-extra fields as-is, but always using lists for extra fields? There will be a lot of single-item lists, but we can also guarantee that a list will always contain at least one item.

**Comment by aw-was-here** [comment]
> I don't think doing this automatically this is a good idea. Returned types should be predictable and consistent, we can't just switch between a string/integer and list.

You could always just make them always lists.

> How about keeping non-extra fields as-is, but always using lists for extra fields? There will be a lot of single-item lists, but we can also guarantee that a list will always contain at least one item.

That sounds reasonable, esp if the non-extra lists also appear in extra as lists.

**Comment by mathiascode** [comment]
Can you test https://github.com/devsnd/tinytag/pull/209 and verify that it works as expected?

New behavior:
- All `extra` attributes are always lists containing one or more values
- Non-extra attributes (e.g. `album`, `artist`, `genre`) store the first value. If any additional values are found for these attributes, they are stored in `extra` lists (e.g. `extra.album`, `extra.artist`, `extra.genre`).

**Comment by aw-was-here** [comment]
Sorry this completely slipped my mind (I was at the Cruel World festival).  I'll try to bang on it here over the weekend.

**Comment by aw-was-here** [comment]
> * Non-extra attributes (e.g. `album`, `artist`, `genre`) store the first value. If any additional values are found for these attributes, they are stored in `extra` lists (e.g. `extra.album`, `extra.artist`, `extra.genre`).

Including the one value that is stored in non-extra, correct?  Just want to verify what I'm seeing.

**Comment by mathiascode** [comment]
> Including the one value that is stored in non-extra, correct? Just want to verify what I'm seeing.

Excluding the first non-extra value (except for `composer`, but I decided to [undeprecate it](https://github.com/devsnd/tinytag/commit/f9bdcc6220b9ab51a9f0c396a08850ddc276246a), which will also fix the behavior there).

The idea is that you use the non-extra fields to get common info about a file as a single value (in part for backwards compatibility, to avoid breakage for every existing user out there, but also for consistency). For more "advanced" use cases, the extra dict provides any remaining, nonduplicate info in the form of lists.

**Comment by aw-was-here** [comment]
Ok then there is either a bug or I'm doing something wrong.  With a track with a single artist, I'm seeing the artist primary value also showing up in extra.

**Comment by mathiascode** [comment]
Should be fixed in the latest revision of the PR.

**Comment by mathiascode** [comment]
> FWIW, it'd make my life easier to just read that one field but in the end appending doesn't make much difference. 😄

You should now be able to do this with `tag.as_dict(flatten=True)`. The `as_dict()` method returns the tag as a dictionary, and the `flatten` parameter merges the fields in the extra dict with the non-extra ones.

**Comment by mathiascode** [comment]
Have you been able to test the latest changes?

**Comment by mathiascode** [comment]
I'll assume the changes in the PR are fine, and merge it. Let me know if something is still missing.

**Comment by mathiascode** [comment]
Updated documentation for 2.0.0 is available here: https://github.com/mathiascode/tinytag/blob/2.0.0-docs/README.md

Let me know if something is unclear, missing or incorrect, and I'll make improvements before the final release.
