### ISSUE TITLE
Support for multiple entries in tags

### ISSUE THREAD

**Issue by Pavel-Sushko** [tinytag/tinytag#215]
**Is your feature request related to a problem? Please describe.**
In tags where there are multiple entries split by `;`, tinytag only pulls the first entry.

**Describe the solution you'd like**
It would be great if tinytag didn't cut the string after encountering a `;`, or even better if instead it returned a list split by the separator.

**Describe alternatives you've considered**
Unfortunately, other than changing the `;` for another separator, I don't see what can be done in the current version.

**Additional context**
Here's an example file parsed through ffprobe (top), and tinytag (bottom):
![image](https://github.com/user-attachments/assets/c1f8b0fb-ea79-435f-8d9c-d1636e9270f9)
---
![image](https://github.com/user-attachments/assets/704f79e4-51c4-4d60-b9a2-9c5b0636613c)

**Comment by mathiascode** [comment]
In the upcoming tinytag 2.0.0 release, additional tags of the same type will be present in the `extra` dict. Please try the master branch and let me know how it works for you.

**Comment by Pavel-Sushko** [comment]
@mathiascode found issue #206 and your [comment](https://github.com/tinytag/tinytag/issues/206#issuecomment-2136924308). The function works just as I need in Python 3.12.4 on Ubuntu!

**Comment by mathiascode** [comment]
Nice! I'll update the documentation and hopefully release 2.0.0 soon-ish.

**Comment by mathiascode** [comment]
Updated documentation for 2.0.0 is available here: https://github.com/mathiascode/tinytag/blob/2.0.0-docs/README.md

Let me know if something is unclear, missing or incorrect, and I'll make improvements before the final release.
