### ISSUE TITLE
Support ratings

### ISSUE THREAD

**Issue by haplo** [tinytag/tinytag#216]
I'm writing a small Python program to parse my music library and generate playlists based on different filters, including tags. Tinytag seemed perfect for my needs (small, read-only, Python-native, no deps) but it has one critical piece missing: it's not reading rating tags. 

tinytag's output:

```
>>> import pprint
>>> from tinytag import TinyTag
>>> tag = TinyTag.get('/home/fidel/Music/Ludovico Einaudi/Le onde/07 - Questa notte.flac')
>>> pprint.pprint(tag.as_dict())
{'album': 'Le onde',
'albumartist': 'Ludovico Einaudi',
'artist': 'Ludovico Einaudi',
'audio_offset': None,
'bitdepth': 16,
'bitrate': 478.5516808573106,
'channels': 2,
'comment': None,
'composer': None,
'disc': '1',
'disc_total': '1',
'duration': 316.3486621315193,
'extra': {'isrc': 'ITB009600686'},
'filesize': 18923648,
'genre': 'Modern Classical',
'samplerate': 44100,
'title': 'Questa notte',
'track': '7',
'track_total': '13',
'year': '1996'}
```

Compare to pytaglib output:

```
>>> import taglib
>>> with taglib.File("/home/fidel/Music/Ludovico Einaudi/Le onde/07 - Questa notte.flac") as song:
...     pprint.pp(song.tags)
...
{'ACOUSTID_ID': ['8309c19b-865c-44bd-b3fe-5dbcca95a86d'],
'ALBUM': ['Le onde'],
'ALBUMARTIST': ['Ludovico Einaudi'],
'ALBUMARTISTSORT': ['Einaudi, Ludovico'],
'ARTIST': ['Ludovico Einaudi'],
'ARTISTS': ['Ludovico Einaudi'],
'ARTISTSORT': ['Einaudi, Ludovico'],
'ASIN': ['B0000268M6'],
'BARCODE': ['743213970226'],
'CATALOGNUMBER': ['74321397022'],
'DATE': ['1996'],
'DISCNUMBER': ['1'],
'DISCTOTAL': ['1'],
'FMPS_PLAYCOUNT': ['1'],
'FMPS_RATING': ['1'],
'FMPS_RATING_AMAROK_SCORE': ['0.5'],
'GENRE': ['Modern Classical'],
'ISRC': ['ITB009600686'],
'LABEL': ['Ricordi Oggi'],
'MEDIA': ['CD'],
'MUSICBRAINZ_ALBUMARTISTID': ['fa34b363-79df-434f-a5b8-be4e6898543f'],
'MUSICBRAINZ_ALBUMID': ['55396529-5a29-4874-a472-073920d48ab7'],
'MUSICBRAINZ_ARTISTID': ['fa34b363-79df-434f-a5b8-be4e6898543f'],
'MUSICBRAINZ_RELEASEGROUPID': ['90598a8a-a424-377f-8f42-81e3d1fa07c7'],
'MUSICBRAINZ_RELEASETRACKID': ['350a9a2d-034f-4dba-9337-169e909b3002'],
'MUSICBRAINZ_TRACKID': ['e3a2edff-0582-4cc4-a4d4-db4bd3bbe052'],
'ORIGINALDATE': ['1996'],
'ORIGINALYEAR': ['1996'],
'RELEASECOUNTRY': ['IT'],
'RELEASESTATUS': ['official'],
'RELEASETYPE': ['album'],
'SCRIPT': ['Latn'],
'TITLE': ['Questa notte'],
'TOTALDISCS': ['1'],
'TOTALTRACKS': ['13'],
'TRACKNUMBER': ['7'],
'TRACKTOTAL': ['13']}```
```

Notice the `FMPS_RATING` tag. It goes from 0.0 to 1.0. Most players map 1.0 to 5 stars, and they sometimes support half stars (e.g. 0.5 is 2-and-half stars).

How hard would it be to add support for ratings? If it's not a lot of work and the tinytag maintainers accept the proposal I wouldn't mind coding it.

**Comment by mathiascode** [comment]
I believe the master branch should already support this (will be released as tinytag 2.0.0 eventually). It adds all detected fields to the `extra` dict. Could you verify?

Note that `as_dict()` now has a `flatten` argument, which is true by default. It merges the `extra` dict with the main one you receive.

**Comment by haplo** [comment]
Thank you for the quick reply @mathiascode, I was away on travel.

As you say, tinytag from master works, I see the ratings in `extra`. :tada:

Do you have any idea when 2.0.0 might be released? I see the milestone as 100% completed, but I bet something else must be getting in the way.

Thanks for your hard work!

**Comment by mathiascode** [comment]
> Do you have any idea when 2.0.0 might be released? I see the milestone as 100% completed, but I bet something else must be getting in the way.

Depends on my personal schedule, but within this year. The main thing left for me to do is update the documentation, other than that it's mostly testing to verify that the API works and does what people need. I want to make sure that tinytag 2.0's API works well, so we don't have to do a tinytag 3.0 anytime soon.

Let me know if you run into any issues or need something else.

**Comment by mathiascode** [comment]
Updated documentation for 2.0.0 is available here: https://github.com/mathiascode/tinytag/blob/2.0.0-docs/README.md

Let me know if something is unclear, missing or incorrect, and I'll make improvements before the final release.

**Comment by haplo** [comment]
Hey @mathiascode, I finally got around to continue my project and I'm working against tinytag 2.0.0. Rating seems to work fine. I will open separate issues for any bugs I find.
